### ISSUE TITLE
Some configuration mistakes in my React-Native project?

### ISSUE THREAD

**Issue by naivehhr** [zalmoxisus/remote-redux-devtools#40]
Hello,I just started using devtools.
I can see the store-tree in Chat ,but I don't see any response in Inspector when I click the Add button...
Thanks
```
const store = createStore(
    reducers,
    initialState,
    compose(
      applyMiddleware(thunk),
      devTools()
    )
  );
```
![1](https://cloud.githubusercontent.com/assets/5243456/17861085/47177870-68c2-11e6-8af7-9739f0437a2b.gif)

**Comment by zalmoxisus** [comment]
Hi,

Usually this happens when you mutate the state. But there could be other problems. If you can provide a minimal repo to reproduce, I'd look into it.

**Comment by zalmoxisus** [comment]
That's related to https://github.com/jhen0409/remote-redux-devtools-on-debugger/issues/14.

In `react-native@0.31` there's a bug, which kills websockets when in dev mode. You have to click "Stop Remote JS Debugging" to get it work.

**Comment by zalmoxisus** [comment]
Seems that problem is solved on `react-native@0.32.0`.
@naivehhr, could you please confirm?

**Comment by naivehhr** [comment]
Thanks for your reply~
Recently a little busy work, I will continue to focus on this problem.
“Stop Remote JS Debugging” didn't work for me, I will be in the futureon react-native@0.32.0 keep trying.☺

**Comment by alfredoreduarte** [comment]
Same here, "Stop Remote JS Debugging" didn't fix it either :(

**Comment by zalmoxisus** [comment]
> only the redux inspector part is blank

Most likely, you don't have `process.env.NODE_ENV === 'development'`. In this case just set [`realtime` parameter](https://github.com/zalmoxisus/remote-redux-devtools#parameters) to `true`, and don;t forget to exclude devtools from production.
