### ISSUE TITLE
Unknown named module: 'crypto'

### ISSUE THREAD

**Issue by Chapurin** [zalmoxisus/remote-redux-devtools#60]
E/ReactNativeJS: Unknown named module: 'crypto'
When i do import import devToolsEnhancer from 'remote-redux-devtools';

**Comment by zalmoxisus** [comment]
Could you please provide a stacktrace? We're not using such module, it should be from some dependencies. Are you running it on Windows 10?

**Comment by HJ29** [comment]
I have the same problem and yes, I run it on Windows 10.

**Comment by zalmoxisus** [comment]
@HJ29, what version of React Native you're using? Could you please try to downgrade to `remote-redux-devtools@0.5.1`.

**Comment by ALWAL12** [comment]
Ironically, I don't know how to copy the stack trace from the emulator, so I took 3 pictures :P

Here, we do not have the problem on Mac, but is problematic on Windows 10 for everyone. I tried downgrading to `0.5.1`, but the problem seems to persist.

**Comment by ALWAL12** [comment]
Ironically, I don't know how to copy the stack trace from my emulator, so I took 3 pictures. :)

We don't have the problem here on Mac, but we do on Windows 10 for everyone (in my team). I tried downgrading the version to `0.5.1`, but it does not seem to solve the problem.

![stack trace-1](https://cloud.githubusercontent.com/assets/6422160/21328627/e7330980-c602-11e6-92dc-b8a96ae68669.PNG)
![stack trace-2](https://cloud.githubusercontent.com/assets/6422160/21328628/e7344bf6-c602-11e6-8c54-22efae43ffb5.PNG)
![stack trace-3](https://cloud.githubusercontent.com/assets/6422160/21328629/e735bd74-c602-11e6-8cf1-7775a8b63188.PNG)

**Comment by zalmoxisus** [comment]
@ALWAL12, thanks for the stack trace. I see it is from `shortid` (from [here](https://github.com/dylang/shortid/blob/master/lib/random/random-byte.js#L3)). It was included in `remote-redux-devtools@0.5.5` (in https://github.com/zalmoxisus/remote-redux-devtools/commit/de93b51ab0e218b66b8cefc7b159ee838cd21d11 and https://github.com/zalmoxisus/remotedev-utils/pull/3), so an earlier version should work.

cc @jhen0409

**Comment by ALWAL12** [comment]
Probably a cache error from my own. I'll downgrade temporary. Thank you for the feedback.

**Comment by jhen0409** [comment]
`shortid` have a fallback for [browser](https://github.com/dylang/shortid/blob/master/lib/random/random-byte-browser.js) ([browser field of package.json](https://github.com/dylang/shortid/blob/master/package.json#L33)), and it works for me on React Native. @ALWAL12 could you provide your React Native version?

**Comment by zalmoxisus** [comment]
@jhen0409, it seems to happen only on Windows as in #39.

**Comment by ALWAL12** [comment]
We use the latest version of React-Native, so `0.39` for now. And we had the issue #39 as well.

**Comment by HJ29** [comment]
I'm using the latest version of react native, downgrade to remote-redux-devtools@0.5.1 make it work.

**Comment by sofwu** [comment]
@jhen0409 I get the same error  between NR 0.38~0.39 only on windows, when ever there is nothing wrong on Mac.

**Comment by zalmoxisus** [comment]
It is related to https://github.com/facebook/react-native/issues/9570. It was fixed in https://github.com/facebook/react-native/commit/4647b62f4de9f41ade680bbb90da7d11e2c79547, and available in `react-native@0.40.0-rc.4`.

Not sure we should wait for `react-native@0.40.0` release, encourage to use `remote-redux-devtools@0.5.1` for windows or downgrade `socketcluster-client` and `remotedev-utils` for now.

**Comment by jhen0409** [comment]
@zalmoxisus looks like this problem isn't resolved, the https://github.com/facebook/react-native/issues/9572 should already land on [0.34](https://github.com/facebook/react-native/blob/0.34-stable/packager/react-packager/src/node-haste/Package.js). I think move the issue to react-native will be better.

> downgrade socketcluster-client and remotedev-utils for now.

For `remotedev-utils`, replace `shortid` will be better for older RN versions, or revert https://github.com/zalmoxisus/remote-redux-devtools/commit/de93b51ab0e218b66b8cefc7b159ee838cd21d11.

**Comment by zalmoxisus** [comment]
@jhen0409, as far as I see, [it was merged just in `v0.40.0-rc.4`](https://github.com/facebook/react-native/commit/4647b62f4de9f41ade680bbb90da7d11e2c79547) not in `0.34`.

@ALWAL12, @HJ29, @sofwu, could you please guys check if the problem persists in `react-native@0.40.0-rc.4`?

**Comment by jhen0409** [comment]
@zalmoxisus I think the tag is meaning included the commit of branches:

![2016-12-23 9 52 15](https://cloud.githubusercontent.com/assets/3001525/21455301/27445f92-c95a-11e6-89b5-b2b6a06eac8b.png)

so it should already in `v0.34.0-rc.0`, `v0.40` should only release nearly two weeks of changes.

**Comment by zalmoxisus** [comment]
@jhen0409 thanks for the clarification. Weird. Then I don't see how [`uuid`'s browser field](https://github.com/kelektiv/node-uuid/blob/master/package.json#L21) (which should be supported) is different from [`shortid` one](https://github.com/dylang/shortid/blob/master/package.json#L33).

**Comment by jhen0409** [comment]
I open a PR https://github.com/facebook/react-native/pull/11641, @zalmoxisus it's why `uuid` worked but `shortid` not. 😂

**Comment by zalmoxisus** [comment]
@jhen0409 that's a great catch! 😃
Thanks for addressing it!

**Comment by BolexLiu** [comment]
@zalmoxisus  To solve the schedule?

**Comment by zalmoxisus** [comment]
@BolexLiu, thanks to @jhen0409, this bug is already fixed in React Native, and it should work on `react-native@0.40.0-rc.6`. If you want to support earlier versions, use `remote-redux-devtools@0.5.1`.

**Comment by BolexLiu** [comment]
@zalmoxisus 
thank you.
But I was doing the same on 0.5.1 and now I'm going to try and clean up the cache to see if it works

**Comment by zalmoxisus** [comment]
`react-native@0.41.0` is out, which includes @jhen0409's fix. Added also a note that you should use `remote-redux-devtools@0.5.0` on Windows for earlier versions support.
